export const QUERY_KEYS = {
  PRODUCT: "PRODUCT",
  PRODUCT_REVIEWS: "PRODUCT_REVIEWS",
  CATEGORIES: "CATEGORIES",
  NEW_PRODUCTS: "NEW_PRODUCTS",
  TOP_PRODUCTS: "TOP_PRODUCTS",
  CART: "CART",
  WISHLIST: "WISHLIST",
};
